name: Auto PR Workflow

on:
  push:
    branches:
      - 'feature/*'  # This should match any branch starting with "feature/"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: feature/update-homepage
          title: 'Auto-created PR'
          body: 'This is an auto-created PR for the feature/update-homepage branch.'
